apiVersion: v1
kind: Pod
metadata:
  name: debbug
spec:
  containers:
    - name: debug
      image: alpine/mongosh
      command: []
      ports:
        - name: web
          containerPort: 80
          protocol: TCP