apiVersion: v1
kind: Pod
metadata:
  name: debbug
spec:
  containers:
    - name: debug
      image: docker.io/tutum/dnsutils
      ports:
        - name: web
          containerPort: 80
          protocol: TCP


# TODO automatic flannel deployment + "sudo ip link delete cni0 type bridge" on workers + coredns restart